# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.api.apisources_api import ApisourcesApi  # noqa: E501
from infodbclient.rest import ApiException


class TestApisourcesApi(unittest.TestCase):
    """ApisourcesApi unit test stubs"""

    def setUp(self):
        self.api = infodbclient.api.apisources_api.ApisourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apisources_create(self):
        """Test case for apisources_create

        """
        pass

    def test_apisources_delete(self):
        """Test case for apisources_delete

        """
        pass

    def test_apisources_list(self):
        """Test case for apisources_list

        """
        pass

    def test_apisources_partial_update(self):
        """Test case for apisources_partial_update

        """
        pass

    def test_apisources_read(self):
        """Test case for apisources_read

        """
        pass

    def test_apisources_update(self):
        """Test case for apisources_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
