# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.models.edition import Edition  # noqa: E501
from infodbclient.rest import ApiException


class TestEdition(unittest.TestCase):
    """Edition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdition(self):
        """Test Edition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = infodbclient.models.edition.Edition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
