# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.api.apilinktags_api import ApilinktagsApi  # noqa: E501
from infodbclient.rest import ApiException


class TestApilinktagsApi(unittest.TestCase):
    """ApilinktagsApi unit test stubs"""

    def setUp(self):
        self.api = infodbclient.api.apilinktags_api.ApilinktagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apilinktags_create(self):
        """Test case for apilinktags_create

        """
        pass

    def test_apilinktags_delete(self):
        """Test case for apilinktags_delete

        """
        pass

    def test_apilinktags_list(self):
        """Test case for apilinktags_list

        """
        pass

    def test_apilinktags_partial_update(self):
        """Test case for apilinktags_partial_update

        """
        pass

    def test_apilinktags_read(self):
        """Test case for apilinktags_read

        """
        pass

    def test_apilinktags_update(self):
        """Test case for apilinktags_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
