# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.models.link import Link  # noqa: E501
from infodbclient.rest import ApiException


class TestLink(unittest.TestCase):
    """Link unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLink(self):
        """Test Link"""
        # FIXME: construct object with mandatory attributes with example values
        # model = infodbclient.models.link.Link()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
