# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.models.link_tag import LinkTag  # noqa: E501
from infodbclient.rest import ApiException


class TestLinkTag(unittest.TestCase):
    """LinkTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkTag(self):
        """Test LinkTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = infodbclient.models.link_tag.LinkTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
