# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.api.apisourcetags_api import ApisourcetagsApi  # noqa: E501
from infodbclient.rest import ApiException


class TestApisourcetagsApi(unittest.TestCase):
    """ApisourcetagsApi unit test stubs"""

    def setUp(self):
        self.api = infodbclient.api.apisourcetags_api.ApisourcetagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apisourcetags_create(self):
        """Test case for apisourcetags_create

        """
        pass

    def test_apisourcetags_delete(self):
        """Test case for apisourcetags_delete

        """
        pass

    def test_apisourcetags_list(self):
        """Test case for apisourcetags_list

        """
        pass

    def test_apisourcetags_partial_update(self):
        """Test case for apisourcetags_partial_update

        """
        pass

    def test_apisourcetags_read(self):
        """Test case for apisourcetags_read

        """
        pass

    def test_apisourcetags_update(self):
        """Test case for apisourcetags_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
