# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.api.apilinks_api import ApilinksApi  # noqa: E501
from infodbclient.rest import ApiException


class TestApilinksApi(unittest.TestCase):
    """ApilinksApi unit test stubs"""

    def setUp(self):
        self.api = infodbclient.api.apilinks_api.ApilinksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apilinks_create(self):
        """Test case for apilinks_create

        """
        pass

    def test_apilinks_delete(self):
        """Test case for apilinks_delete

        """
        pass

    def test_apilinks_list(self):
        """Test case for apilinks_list

        """
        pass

    def test_apilinks_partial_update(self):
        """Test case for apilinks_partial_update

        """
        pass

    def test_apilinks_read(self):
        """Test case for apilinks_read

        """
        pass

    def test_apilinks_update(self):
        """Test case for apilinks_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
