# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.api.apiinfsourcetags_api import ApiinfsourcetagsApi  # noqa: E501
from infodbclient.rest import ApiException


class TestApiinfsourcetagsApi(unittest.TestCase):
    """ApiinfsourcetagsApi unit test stubs"""

    def setUp(self):
        self.api = infodbclient.api.apiinfsourcetags_api.ApiinfsourcetagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apiinfsourcetags_create(self):
        """Test case for apiinfsourcetags_create

        """
        pass

    def test_apiinfsourcetags_delete(self):
        """Test case for apiinfsourcetags_delete

        """
        pass

    def test_apiinfsourcetags_list(self):
        """Test case for apiinfsourcetags_list

        """
        pass

    def test_apiinfsourcetags_partial_update(self):
        """Test case for apiinfsourcetags_partial_update

        """
        pass

    def test_apiinfsourcetags_read(self):
        """Test case for apiinfsourcetags_read

        """
        pass

    def test_apiinfsourcetags_update(self):
        """Test case for apiinfsourcetags_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
