# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import infodbclient
from infodbclient.api.apiinfsources_api import ApiinfsourcesApi  # noqa: E501
from infodbclient.rest import ApiException


class TestApiinfsourcesApi(unittest.TestCase):
    """ApiinfsourcesApi unit test stubs"""

    def setUp(self):
        self.api = infodbclient.api.apiinfsources_api.ApiinfsourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apiinfsources_create(self):
        """Test case for apiinfsources_create

        """
        pass

    def test_apiinfsources_delete(self):
        """Test case for apiinfsources_delete

        """
        pass

    def test_apiinfsources_list(self):
        """Test case for apiinfsources_list

        """
        pass

    def test_apiinfsources_partial_update(self):
        """Test case for apiinfsources_partial_update

        """
        pass

    def test_apiinfsources_read(self):
        """Test case for apiinfsources_read

        """
        pass

    def test_apiinfsources_update(self):
        """Test case for apiinfsources_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
