# coding: utf-8

# flake8: noqa

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from infodbclient.api.api_token_auth_api import ApiTokenAuthApi
from infodbclient.api.apieditions_api import ApieditionsApi
from infodbclient.api.apiinfsources_api import ApiinfsourcesApi
from infodbclient.api.apiresources_api import ApiresourcesApi

# import ApiClient
from infodbclient.api_client import ApiClient
from infodbclient.configuration import Configuration
# import models into sdk package
from infodbclient.models.auth_token import AuthToken
from infodbclient.models.edition import Edition
from infodbclient.models.infsource import Infsource
from infodbclient.models.resource import Resource
