# coding: utf-8

# flake8: noqa
"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from infodbclient.models.auth_token import AuthToken
from infodbclient.models.link import Link
from infodbclient.models.link_tag import LinkTag
from infodbclient.models.source import Source
from infodbclient.models.source_tag import SourceTag
